apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: world-gateway
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      hostname: world.universe.mine
      protocol: HTTP
      port: 80
