apiVersion: v1
kind: Pod
metadata:
    name: simple-webapp-color
    labels:
      name: simple-webapp-color
spec:
  containers:
    - name: simple-webbapp-color-container
      image: kodekloud/webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_COLOR 
---
apiVersion: v1
kind: Service 
metadata:
  name: simple-webapp-color-svc
spec:
  type: ClusterIP
  selector:
    name: simple-webapp-color
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080
