apiVersion: v1
kind: Pod 
metadata:
  name: secret-pod-v1
  label:
    secret-pod: v1

spec:
  containers:
    - name: secret-contianer-v1
      image: nginx
      envFrom:
        - secretRef:
            name: app-secret

      env:
        - name: DB_Host
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Host


      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret
