apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
spec:
  region: us-east-1
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-credentials
      key: ""
  endpoint:
    url:
      type: Static
      static: http://host.docker.internal:4566
    source: Custom
