apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials
  endpoint:
    source: Custom
    hostnameImmutable: true
    signingRegion: us-west-2
    partitionId: aws
    url:
      type: Static
      static: http://172.17.0.1:4566

      # going to gateway of dns and going outside on the port that is exposed on host

