---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-secret-payload
  namespace: crossplane-system
type: Opaque
stringData:
  value: |
    {
      "username": "admin",
      "password": "supersecret"
    }

---
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: localstack-secret
  annotations:
    crossplane.io/external-name: localstack-demo-secret
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: localstack
  forProvider:
    region: us-east-1
    description: "Secret managed by Crossplane against LocalStack"
    stringSecretRef:
      namespace: crossplane-system
      name: localstack-secret-payload
      key: value
