apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    environment: {{ .Values.environment | lower }}
    team: {{ .Values.team | lower }}
    fullname: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      name: simple-pod
      labels:
        app: simple
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
            items:
              - key: configData
                path: app.conf

      containers:
        - name: busybox
          image: {{ .Values.image }}

          volumeMounts:
            - name: config
              mountPath: /app/config/app.conf
              subPath: app.conf
              readOnly: true

          command:
{{ toYaml .Values.command | nindent 12 }}

          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}

{{- range .Values.envSecrets }}
{{- $secretName := .secretName }}
{{- range .keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . }}
{{- end }}
{{- end }}

{{- if .Values.sidecar.enabled }}
        - name: sidecar
          image: nginx
          ports:
            - name: http
              containerPort: {{ default 80 .Values.sidecar.port }}
{{- end }}
