{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webapp.labels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "webapp.fullname" . }}
      automountServiceAccountToken: true
      {{- end }}
      

      {{- if .Values.monitoring.enabled }}
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        envFrom:
        {{- range .Values.envFromConfigMaps }}
        - configMapRef:
            name: {{ include "webapp.fullname" $ }}-{{ .name }}
        {{- end }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          valueFrom:
            fieldRef:
              fieldPath: {{ .valueFrom.fieldRef.fieldPath }}
        {{- end }}
        command:
          {{- toYaml .Values.command | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep sleep || exit 1
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep sleep || exit 1
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
