{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  metadata:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    {{- include "webapp.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.servicePort }}
    targetPort: http
{{- end }}