apiVersion: apps/v1
kind: Deployment 
metadata:
  name: enter-sandman-override
  namespace: metallica
spec:
  template:
    metadata:
      name: sandman-pod-override 
      labels:
        app: sandman-override
    spec:
      containers:
        - name: sandman
          image: nginx
          ports:
            - containerPort: 80 
              name: http
          volumeMounts:
            - name: metal-vol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: metal-vol
          configMap:
            name: metal-cm
  replicas: 2
  selector:
    matchLabels:
      app: sandman-override
