apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mockingtools
  labels:
    app: mockapi
spec:
  template:
    metadata:
      labels:
        app: mockapi
    spec:
      containers:
      - name: mockapi-container
        image: wiremock/wiremock:2.35.0
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: mockapi
  replicas: 4

---
apiVersion: v1
kind: Service 
metadata:
  name: mockapi-clusterip-svc
spec:
  type: ClusterIP 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080
  selector:
    app: mockapi 
---
apiVersion: v1
kind: Service 
metadata:
  name: mockapi-lb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: mockapi
