{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
data:
  app-name: {{ .Values.appName }}
  chart-name: {{ .Chart.Name }}
  chart-version: {{ .Chart.Version }}
{{- end }}