apiVersion: v1
kind: ConfigMap
metadata:
  name: timeless
data:
  city: on 5 when i am coming home, it fill up the sky
  yap: Carti coming in with 99 different voices
  legit: |
    I'm 58 years old. Last week, I went to the After Hours Till Dawn concert with my younger coworkers. I was feeling intimidated they convinced me to go. The best experience I had in a very long time. I felt young again carefree. I could feel the energy of all the young people around me. I am so thankful for the experience. ❤
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: are-you-bored-yet
data:
  lyrics: |
    if you can tell me how you felling
    maybe we can get through this undefeated
    we can stay home and watch the sunset
  comment: nostalgaic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: no-one-knows
data:
  music: |
    no one knows the trouble honey
    that we have been through, still
    i know ... 
  comment1: stephen AND laufey?? i’m going insane this is such a legendary collab
  comment2: |
    Thank both you and laufey for reviving older genres of music for our generation!!!  I’ve always felt like an outlier listening to Frank Sinatra, The Platters, Ella Fitzgerald etc in my friend group and I’m happy to see the older styles make a come back!
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  app.conf: ZGtzamRsZmpzbAo=
  localhost: ZGtzamRsZmpzbAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: dil-mere
type: Opaque
data:
  username: dXNlcg==
  password: cGFzc3dvcmQ=
  hmmm: aG1tIG5hbiBhbmFuLCBkaWwgbWVyZSBiYXphcm8gbWUK
---
apiVersion: v1
kind: Secret 
metadata:
  name: cz-stonecold-said-so
type: Opaque
data:
  thats: dGhlIGJvdHRvbWxpbmUK
  what: d2hhdAo=
---
apiVersion: v1
kind: Pod
metadata:
  name: muzik
spec:
  volumes:
    - name: cz-stonecold-said-so
      secret:
        secretName: cz-stonecold-said-so
        items:
          - key: what
            path: what.conf
            mode: 0400
          - key: thats
            path: thats
    - name: app-store
      secret:
        secretName: app-secret
        defaultMode: 0400
    - name: pshyc-it-dont-exist
      secret:
        secretName: dont-exist
        optional: true
    - name: local-train
      secret:
        secretName: dil-mere
    - name: weekend
      configMap:
        name: timeless
    - name: wallows
      configMap:
        name: are-you-bored-yet 
    - name: stephan 
      configMap:
        name: no-one-knows
        items:
          - key: music
            path: music
          - key: comment1
            path: comment1
          - key: comment2
            path: comment2
  containers:
    - image: busybox
      name: busybox
      command: ["sleep","3600"]
      volumeMounts:
        - name: cz-stonecold-said-so
          mountPath: /mnt/cz-stonecold-said-so
        - name: app-store
          mountPath: /mnt/app-store
        - name: pshyc-it-dont-exist 
          mountPath: /mnt/phsyc-it-dont-exist
        - name: local-train
          mountPath: /mnt/local-train 
        - name: stephan
          mountPath: /mnt/stephan
        - name: wallows
          mountPath: /mnt/wallows
        - name: weekend
          mountPath: /mnt/weekend/legit
          subPath: legit
