apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: static
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: automatic
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: storage-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defined-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: dynamic
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storal-pv
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  storageClassName: dynamic
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: my
            operator: In
            values: ["man"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storal-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: dynamic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exotic
spec:
  storageClassName: glusterfile 
  accessModes: ["ReadWriteMany"]
  resources: { "requests": {"storage": "1Gi"}}
