apiVersion: v1
kind: Pod 
metadata:
  name: boron
spec:
  volumes:
    - name: shared
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  containers:
    - name: one
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: shared
          mountPath: /mnt/data
          subPath: one
    - name: two
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: shared
          mountPath: /mnt/data
          subPath: two

