apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: vikashraj1825/api-demo:1.0.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo
  namespace: playground
spec:
  selector:
    app: api-demo
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
