apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: ClusterIP
  selector:
    app: simple
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: {{ default "TCP" .Values.service.protocol }}
      targetPort: {{ default .Values.service.port .Values.service.targetPort }}
