apiVersion: v1
kind: Service
metadata:
  name: asia
spec:
  type: ClusterIP
  selector:
    app: asia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: world
  namespace: world
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: world.universe.mine
    http:
      paths:
        - path: /asia
          pathType: Prefix
          backend:
            service:
              name: asia
              port:
                number: 80
        - path: /europe
          pathType: Prefix
          backend:
            service:
              name: europe
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: europe
spec:
  type: ClusterIP
  selector:
    app: europe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

