# controlplane:~$ k get pods
# NAME                                READY   STATUS    RESTARTS   AGE
# nginx-deployment-6cfb98644c-s6bjh   1/1     Running   0          4m48s
# controlplane:~$ k get svc
# NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
# kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP   6d4h
# nginx-service   ClusterIP   10.103.170.183   <none>        80/TCP    4m53s
# controlplane:~$ k get ingress
# NAME                     CLASS   HOSTS   ADDRESS   PORTS   AGE
# nginx-ingress-resource   nginx   *                 80      20s
# controlplane:~$ k get -A      
# You must specify the type of resource to get. Use "kubectl api-resources" for a complete list of supported resources.

# error: Required resource not specified.
# Use "kubectl explain <resource>" for a detailed description of that resource (e.g. kubectl explain pods).
# See 'kubectl get -h' for help and examples
# controlplane:~$ k get all
# NAME                                    READY   STATUS    RESTARTS   AGE
# pod/nginx-deployment-6cfb98644c-s6bjh   1/1     Running   0          5m7s

# NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
# service/kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP   6d4h
# service/nginx-service   ClusterIP   10.103.170.183   <none>        80/TCP    5m7s

# NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
# deployment.apps/nginx-deployment   1/1     1            1           5m7s

# NAME                                          DESIRED   CURRENT   READY   AGE
# replicaset.apps/nginx-deployment-6cfb98644c   1         1         1       5m7s
# controlplane:~$ k get ns
# NAME                 STATUS   AGE
# default              Active   6d4h
# kube-node-lease      Active   6d4h
# kube-public          Active   6d4h
# kube-system          Active   6d4h
# local-path-storage   Active   6d4h
# controlplane:~$ cat ingress.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-resource
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /shop
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80
