apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smoke-applications-admin
  namespace: applications
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smoke-applications-admin-binding
  namespace: applications
subjects:
- kind: User
  name: smoke
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: smoke-applications-admin
  apiGroup: rbac.authorization.k8s.io

---



# for ns in $(kubectl get ns --no-headers -o custom-columns=:metadata.name | grep -v kube-system); do
#   kubectl create rolebinding smoke-view-binding \
#     --clusterrole=view \
#     --user=smoke \
#     -n $ns
# done

