apiVersion: v1
kind: Pod
metadata:
  name: "important"
  namespace: lion
  labels:
    app: "important"
spec:
  containers:
  - name: important
    image: "nginx:1.21.6-alpine"
    resources:
      limits:
        memory: 1Gi
    ports:
    - containerPort:  80
      name:  http
  priorityClassName: level3
  restartPolicy: Always