apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod-pod
spec:
  restartPolicy: Never
  containers:
    - name: alpine-container
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - tail -f /config/log.txt
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: log-configmap


# awk 'NR==2 {print $2 "," $1}'

# kubectl top nodes --sort-by=memory | awk 'NR==2 {print c","$1}' c=$(kubectl config current-context) > /root/high_memory_node.txt
