apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: configurator
  namespace: configurator
spec:
  selector:
    matchLabels:
      app: configurator
  template:
    metadata:
      labels:
        app: configurator
    spec:
      containers:
      - name: bash
        image: bash
        command: ["/bin/sh", "-c"]
        args:
          - echo "aba997ac-1c89-4d64" > /configurator/config && sleep 1d
        volumeMounts:
        - name: local-fs
          mountPath: /configurator
      volumes:
      - name: local-fs
        hostPath:
          path: /configurator 
          type: DirectoryOrCreate

