apiVersion: v1
kind: Pod
metadata:
  name: hobby-project
  labels:
    level: hobby
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              level: restricted
          topologyKey: kubernetes.io/hostname
  containers:
  - name: c
    image: nginx:alpine
