# controlplane:~$ cat /tmp/kubectl-edit-321022382.yaml 
# # Please edit the object below. Lines beginning with a '#' will be ignored,
# # and an empty file will abort the edit. If an error occurs while saving this file will be
# # reopened with the relevant failures.
# #
# # pods "my-pod-cka" was not valid:
# # * patch: Invalid value: "map[spec:map[]]": strict decoding error: unknown field "spec.containers[1].commands"
# #
# apiVersion: v1
# kind: Pod
# metadata:
#   annotations:
#     cni.projectcalico.org/containerID: b692a479b394487dbfd58a781e060a859655390ebaa254841f66d02e478cbfe5
#     cni.projectcalico.org/podIP: 192.168.1.5/32
#     cni.projectcalico.org/podIPs: 192.168.1.5/32
#     kubectl.kubernetes.io/last-applied-configuration: |
#       {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"my-pod-cka","namespace":"default"},"spec":{"containers":[{"image":"nginx","name":"nginx-container","volumeMounts":[{"mountPath":"/var/www/html","name":"shared-storage"}]}],"volumes":[{"name":"shared-storage","persistentVolumeClaim":{"claimName":"my-pvc-cka"}}]}}
#   creationTimestamp: "2025-08-25T15:16:12Z"
#   generation: 1
#   name: my-pod-cka
#   namespace: default
#   resourceVersion: "2998"
#   uid: b75bea7a-7193-43dc-b72d-cc27b839cea2
# spec:
#   containers:
#   - image: nginx
#     imagePullPolicy: Always
#     name: nginx-container
#     resources: {}
#     terminationMessagePath: /dev/termination-log
#     terminationMessagePolicy: File
#     volumeMounts:
#     - mountPath: /var/www/html
#       name: shared-storage
#     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#       name: kube-api-access-srl2s
#       readOnly: true
#   - image: busybox
#     name: busybox
#     command: ["tail"]
#     args: ["-f /dev/null"]
#     volumeMounts:
#     - mountPath: /var/www/shared
#       name: shared-storage
#       readOnly: true
#   dnsPolicy: ClusterFirst
#   enableServiceLinks: true
#   nodeName: node01
#   preemptionPolicy: PreemptLowerPriority
#   priority: 0
#   restartPolicy: Always
#   schedulerName: default-scheduler
#   securityContext: {}
#   serviceAccount: default
#   serviceAccountName: default
#   terminationGracePeriodSeconds: 30
#   tolerations:
#   - effect: NoExecute
#     key: node.kubernetes.io/not-ready
#     operator: Exists
#     tolerationSeconds: 300
#   - effect: NoExecute
#     key: node.kubernetes.io/unreachable
#     operator: Exists
#     tolerationSeconds: 300
#   volumes:
#   - name: shared-storage
#     persistentVolumeClaim:
#       claimName: my-pvc-cka
#   - name: kube-api-access-srl2s
#     projected:
#       defaultMode: 420
#       sources:
#       - serviceAccountToken:
#           expirationSeconds: 3607
#           path: token
#       - configMap:
#           items:
#           - key: ca.crt
#             path: ca.crt
#           name: kube-root-ca.crt
#       - downwardAPI:
#           items:
#           - fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.namespace
#             path: namespace
# status:
#   conditions:
#   - lastProbeTime: null
#     lastTransitionTime: "2025-08-25T15:16:31Z"
#     status: "True"
#     type: PodReadyToStartContainers
#   - lastProbeTime: null
#     lastTransitionTime: "2025-08-25T15:16:20Z"
#     status: "True"
#     type: Initialized
#   - lastProbeTime: null
#     lastTransitionTime: "2025-08-25T15:16:31Z"
#     status: "True"
#     type: Ready
#   - lastProbeTime: null
#     lastTransitionTime: "2025-08-25T15:16:31Z"
#     status: "True"
#     type: ContainersReady
#   - lastProbeTime: null
#     lastTransitionTime: "2025-08-25T15:16:20Z"
#     status: "True"
#     type: PodScheduled
#   containerStatuses:
#   - containerID: containerd://849b7f0e2847e6f87da85c91dcf3a879dd7d752b574b3a697ee625baf3ffced0
#     image: docker.io/library/nginx:latest
#     imageID: docker.io/library/nginx@sha256:33e0bbc7ca9ecf108140af6288c7c9d1ecc77548cbfd3952fd8466a75edefe57
#     lastState: {}
#     name: nginx-container
#     ready: true
#     resources: {}
#     restartCount: 0
#     started: true
#     state:
#       running:
#         startedAt: "2025-08-25T15:16:31Z"
#     volumeMounts:
#     - mountPath: /var/www/html
#       name: shared-storage
#     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#       name: kube-api-access-srl2s
#       readOnly: true
#       recursiveReadOnly: Disabled
#   hostIP: 172.30.2.2
#   hostIPs:
#   - ip: 172.30.2.2
#   phase: Running
#   podIP: 192.168.1.5
#   podIPs:
#   - ip: 192.168.1.5
#   qosClass: BestEffort
#   startTime: "2025-08-25T15:16:20Z"
# controlplane:~$ 