# controlplane:~$ ls
# filesystem
# controlplane:~$ k get pvc
# NAME             STATUS   VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE
# yellow-pvc-cka   Bound    yellow-pv-cka   100Mi      RWO            yellow-stc-cka   <unset>                 116s
# controlplane:~$ k get pv
# NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
# yellow-pv-cka   100Mi      RWO            Retain           Bound    default/yellow-pvc-cka   yellow-stc-cka   <unset>                          119s
# controlplane:~$ kubectl patch pv yellow-pv-cka \
#   -p '{"spec":{"capacity":{"storage":"60Mi"}}}'
# persistentvolume/yellow-pv-cka patched
# controlplane:~$ kubectl patch pvc yellow-pvc-cka \
#   -p '{"spec":{"resources":{"requests":{"storage":"60Mi"}},"volumeName":"yellow-pv-cka"}}'
# persistentvolumeclaim/yellow-pvc-cka patched
# controlplane:~$ kubectl get pvc yellow-pvc-cka
# kubectl describe pvc yellow-pvc-cka | egrep 'Status:|Volume:|Capacity:|Requests:'
# NAME             STATUS   VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE
# yellow-pvc-cka   Bound    yellow-pv-cka   100Mi      RWO            yellow-stc-cka   <unset>                 2m35s
# Status:        Bound
# Volume:        yellow-pv-cka
# Capacity:      100Mi
# controlplane:~$ 
