apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-cka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data
  capacity:
    storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-cka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Mi
  storageClassName: standard
  volumeName: my-pv-cka
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-cka
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-pvc-cka
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: storage
          mountPath: /var/www/html