apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prefix-route
  namespace: world 
spec:
  parentRefs:
    - name: prefix-gateway
      namespace: world
  hostnames:
    - "app.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: api-demo
          port: 5000
