apiVersion: apps/v1
kind: Deployment 
metadata:
  name: debugger
  labels:
    app: echo
    month: july
spec:
  template:
    metadata:
      name: debugger-pod
      labels:
        app: echo 
        month: july
    spec:
      containers:
      - name: debugger-container
        image: hashicorp/http-echo:0.2.3
        ports:
        - containerPort: 5678
        args:
        - "-text=hello from the echo squad"
  replicas: 3
  selector:
    matchLabels:
      app: echo

---
apiVersion: v1 
kind: Service 
metadata:
  name: debugger-svc
  labels:
    app: echo
spec:
  type: ClusterIP     
  selector:
    app: echo 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678

---
apiVersion: v1
kind: Service 
metadata:
  name: echo-nodeport
spec:
  selector: 
    app: echo 
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 30080
---

apiVersion: v1
kind: Service 
metadata:
  name: echo-lb
spec:
  selector:
    app: echo
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 5678
