apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-pv-cka
spec:
  storageClassName: fast-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /tmp/fast-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-pvc-cka
spec:
  resources:
    requests:
      storage: 30Mi
  storageClassName: fast-storage
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: fast-pod-cka
spec:
  containers:
  - name: fast-container
    image: nginx:latest
    volumeMounts:
    - name: shared-storage
      mountPath: /app/data
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: fast-pvc-cka
